Street_Vendors/Street_Vendors/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Street_Vendors.Models;

namespace Street_Vendors.Controllers
{
    [Authorize]
    public class ItemsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Items
        public ActionResult Index()
        {
            var items = db.Items.Include(i => i.ApplicationUser);

            var id = User.Identity.GetUserId();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            ViewBag.user = user;

            return View(items.ToList());
        }

        // GET: Items/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: Items/Create
        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email");
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ItemName,ItemDescription,ItemPrice,ItemImage,ItemRating,UserId")] Item item, HttpPostedFileBase ImageFile)
        {
            if (ModelState.IsValid)
            {
                foreach (string img in Request.Files)
                {
                    ImageFile = Request.Files[img];
                    string extension = Path.GetExtension(ImageFile.FileName);

                    if (extension.ToLower() == ".jpg" || extension.ToLower() == ".jpeg" || extension.ToLower() == ".png")
                    {
                        if (ImageFile != null && ImageFile.ContentLength > 0)
                        {

                            string file_name = Path.GetFileNameWithoutExtension(ImageFile.FileName) + Path.GetExtension(ImageFile.FileName);

                            string path = Path.Combine(Server.MapPath("~/image"), file_name);
                            ImageFile.SaveAs(path);
                            item.ItemImage = "~/image/" + file_name;

                            db.Items.Add(item);
                            db.SaveChanges();
                            return RedirectToAction("Index");
                        }
                    }
                    else
                    {
                        TempData["msg"] = "Invalid File Type";

                    }
                }
                ModelState.Clear();



                //db.Items.Add(item);
                //db.SaveChanges();
                //return RedirectToAction("Index");
            }

            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", item.UserId);
            return View(item);
        }

        // GET: Items/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            Session["imgPath"] = item.ItemImage;
            if (item == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", item.UserId);
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ItemName,ItemDescription,ItemPrice,ItemImage,ItemRating,UserId")] Item item, HttpPostedFileBase ImageFile)
        {
            if (ImageFile != null)
            {
                if (ModelState.IsValid)
                {
                    foreach (string img in Request.Files)
                    {
                        ImageFile = Request.Files[img];
                        string extension = Path.GetExtension(ImageFile.FileName);

                        if (extension.ToLower() == ".jpg" || extension.ToLower() == ".jpeg" || extension.ToLower() == ".png")
                        {
                            if (ImageFile.ContentLength > 0)
                            {

                                string file_name = Path.GetFileNameWithoutExtension(ImageFile.FileName) + Path.GetExtension(ImageFile.FileName);

                                string path = Path.Combine(Server.MapPath("~/image"), file_name);
                                ImageFile.SaveAs(path);
                                item.ItemImage = "~/image/" + file_name;

                                db.Entry(item).State = EntityState.Modified;
                                string oldImgPath = Request.MapPath(Session["imgPath"].ToString());
                                db.SaveChanges();

                                if (System.IO.File.Exists(oldImgPath))
                                {
                                    System.IO.File.Delete(oldImgPath);
                                }
                                TempData["msg"] = "Data Updated";
                                return RedirectToAction("Index");
                            }
                        }
                        else
                        {
                            TempData["msg"] = "Invalid File Type";

                        }

                    }
                    ModelState.Clear();
                }
                ViewBag.UserId = new SelectList(db.Users, "Id", "Email", item.UserId);
                return View(item);
            }

            else
            {
                item.ItemImage = Session["imgPath"].ToString();
                db.Entry(item).State = EntityState.Modified;
                if (db.SaveChanges() > 0)
                {
                    TempData["msg"] = "Data Updated";
                    return RedirectToAction("Index");
                }

            }
            /*
            if (ModelState.IsValid)
            {
                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            */
            //ViewBag.UserId = new SelectList(db.ApplicationUsers, "Id", "Email", item.UserId);
            return View(item);
        }

        // GET: Items/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Item item = db.Items.Find(id);
            string currentImg = Request.MapPath(item.ItemImage);
            if (System.IO.File.Exists(currentImg))
            {
                System.IO.File.Delete(currentImg);
            }
            db.Items.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Street_Vendors/Street_Vendors/Controllers/MarketPlaceController.cs
using Street_Vendors.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Street_Vendors.Controllers
{
    [Authorize]
    public class MarketPlaceController : Controller
    {
        private ApplicationDbContext _context = new ApplicationDbContext();
        public MarketPlaceController()
        {

        }
        // GET: MarketPlace
        public ActionResult Index()
        {
            ViewBag.sellers = _context.Users.ToList();
            ViewBag.items = _context.Items.ToList();
            return View();
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = _context.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }
        public ActionResult ProfileDetails(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = _context.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            ViewBag.items = _context.Items.ToList();
            return View(user);
        }

        public ActionResult likeItem(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = _context.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            item.ItemRating += 1;
            _context.SaveChanges();
            return RedirectToAction("Details", new { id });
        }

        public ActionResult dislikeItem(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = _context.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            item.ItemRating -= 1;
            _context.SaveChanges();
            return RedirectToAction("Details", new { id });
        }
    }
}

Street_Vendors/Street_Vendors/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Street Vendors</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @* Edited file\library*@
    <link rel="stylesheet" href="~/Content/Welcome.css" />
    <script src='https://kit.fontawesome.com/0d5b94f051.js' crossorigin='anonymous'></script>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">


</head>
<body>
    @Html.Partial("_navWelcome")
    <ul class="bubble-boxes">
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
    </ul>
    <div class="container-fluid bodyrender">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Street Vendors Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    @* Edited part *@


    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
        AOS.init(0);
    </script>

</body>
</html>

Street_Vendors/Street_Vendors/Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Street Vendors</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @* Edited file\library*@
    <link rel="stylesheet" href="~/Content/Home.css" />

    <script src='https://kit.fontawesome.com/0d5b94f051.js' crossorigin='anonymous'></script>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">


</head>
<body>
    @Html.Partial("_navHome")
    <div class="container-fluid bodyrender">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Street Vendors Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    @* Edited part *@

    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
        AOS.init(0);
    </script>

</body>
</html>

Street_Vendors/Street_Vendors/Views/Shared/_filterView.cshtml
<div class="card mt-5 position-fixed">
    <div class="card-body">
        <div class="row">
            <div class="input-group mb-3">
                <input type="text" class="form-control" placeholder="Search">
                <div class="input-group-append">
                    <button class="btn btn-success" type="submit"><i class="fas fa-search"></i> Search</button>
                </div>
            </div>
        </div>
        
        <img src="~/images/filter/veg_1.png" class="border border-primary rounded-circle img-fluid" height="50" width="50" />

        <img src="~/images/filter/cloth_1.png" class="border border-primary rounded-circle img-fluid m-4" height="50" width="50" />
        <img src="~/images/filter/fish_1.png" class="border border-primary rounded-circle img-fluid m-4" height="50" width="50" />
        

    </div>
</div>

Street_Vendors/Street_Vendors/Views/Shared/_navHome.cshtml
<nav class="navbar navbar-expand-md navbar-inverse fixed-top">
    @Html.ActionLink("Street Vendors", "Index", "Home", new { area = "" }, new { @class = "navbar-brand btn btn-outline-light text-info mr-3" })
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
            <li class="nav-item">
                @Html.ActionLink("Market Place", "Index", "MarketPlace", new { area = "" }, new { @class = "btn btn-outline-info mr-md-4" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Map", "Index", "Map", new { area = "" }, new { @class = "btn btn-outline-info mr-md-4" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("My Shop", "Index", "Items", new { area = "" }, new { @class = "btn btn-outline-info mr-md-4" })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Community", "Index", "Community", new { area = "" }, new { @class = "btn btn-outline-info mr-md-4" })
            </li>
        </ul>
        @Html.Partial("_LoginPartial")
    </div>
</nav>

Street_Vendors/Street_Vendors/Views/Shared/_navWelcome.cshtml
<nav class="navbar navbar-expand-md navbar-inverse fixed-top">
    @Html.ActionLink("Street Vendors", "Index", "Home", new { area = "" }, new { @class = "navbar-brand btn btn-outline-light text-info mr-3" })
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="btn btn-outline-info mr-md-4" href="#section1">Home</a>
            </li>
            <li class="nav-item">
                <a class="btn btn-outline-info mr-md-4" href="#section2">About Us</a>
            </li>
            <li class="nav-item">
                <a class="btn btn-outline-info mr-md-4" href="#section3">Contact Us</a>
            </li>
        </ul>
        @Html.Partial("_LoginPartial")
    </div>
</nav>